{{ if and (eq .Values.robot_authentication "true") (eq .Values.fluentbit "true") }}
---
# Source: fluent-bit/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  labels:
    helm.sh/chart: fluent-bit-0.20.5
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/version: "1.9.7"
    app.kubernetes.io/managed-by: Helm
---
# Source: fluent-bit/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit
  labels:
    helm.sh/chart: fluent-bit-0.20.5
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/version: "1.9.7"
    app.kubernetes.io/managed-by: Helm
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
    
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
    
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
    
    [INPUT]
        Name systemd
        Tag k8s_node.${MY_NODE_NAME}
        Systemd_Filter  _SYSTEMD_UNIT=containerd.service
        Systemd_Filter  _SYSTEMD_UNIT=etcd.service
        Systemd_Filter  _SYSTEMD_UNIT=kube-apiserver.service
        Systemd_Filter  _SYSTEMD_UNIT=kube-controller-manager.service
        Systemd_Filter  _SYSTEMD_UNIT=kube-scheduler.service
        Systemd_Filter  _SYSTEMD_UNIT=kubelet.service
        Systemd_Filter  _SYSTEMD_UNIT=sshd.service
        Read_From_Tail On
    
    [INPUT]
        name            node_exporter_metrics
        tag             node_metrics
        scrape_interval 10
    
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
    
    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals level info
        Add severity INFO
    
    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals level warning
        Add severity WARNING
    
    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals level warn
        Add severity WARNING
    
    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals level error
        Add severity ERROR
    
    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log ^.*\[\sinfo\].*$
        Add severity INFO
    
    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log ^.*\[\swarn\].*$
        Add severity WARNING
    
    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log .*\[error\].*
        Add severity ERROR
    
    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log .*(type="Info"|level=info).*
        Add severity INFO
    
    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log .*(type="Warning"|level=warning).*
        Add severity WARNING
    
    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log .*(type="Error"|level=error).*
        Add severity ERROR
    
    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals stream stderr
        Add severity ERROR
    
    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals stream stdout
        Add severity INFO
    
    [FILTER]
        Name          modify
        Match         kube.*
        Remove _p
    
    [FILTER]
        Name          modify
        Match         kube.*
        Rename log message
    
    [OUTPUT]
        Name stackdriver
        Match kube.*
        Tag_Prefix kube.var.log.containers.
        Resource k8s_container
        k8s_cluster_name {{ .Values.robot.name }}
        k8s_cluster_location europe-west1-c
        severity_key severity
        Workers 1
    
    [OUTPUT]
        Name stackdriver
        Match k8s_node.*
        Resource k8s_node
        custom_k8s_regex ^(?<node_name>.*)$
        k8s_cluster_name {{ .Values.robot.name }}
        k8s_cluster_location europe-west1-c
        Workers 1
    
    [OUTPUT]
        name            prometheus_exporter
        match           node_metrics
        port            24231
---
# Source: fluent-bit/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
  labels:
    helm.sh/chart: fluent-bit-0.20.5
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/version: "1.9.7"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
---
# Source: fluent-bit/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
  labels:
    helm.sh/chart: fluent-bit-0.20.5
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/version: "1.9.7"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: default
---
# Source: fluent-bit/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  labels:
    helm.sh/chart: fluent-bit-0.20.5
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/version: "1.9.7"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 2020
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
---
# Source: fluent-bit/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  labels:
    helm.sh/chart: fluent-bit-0.20.5
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/version: "1.9.7"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
      app.kubernetes.io/instance: fluent-bit
  template:
    metadata:
      annotations:
        checksum/config: a37b935cef9054ddc883c0b72534c541794e7ac171c311b6e532b8daf290b1d0
        checksum/luascripts: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      labels:
        app.kubernetes.io/name: fluent-bit
        app.kubernetes.io/instance: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      hostNetwork: false
      dnsPolicy: ClusterFirst
      containers:
        - name: fluent-bit
          image: "cr.fluentbit.io/fluent/fluent-bit:1.9.7"
          imagePullPolicy: IfNotPresent
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          volumeMounts:
            - mountPath: /fluent-bit/etc/fluent-bit.conf
              name: config
              subPath: fluent-bit.conf
            - mountPath: /var/log
              name: varlog
            - mountPath: /etc/machine-id
              name: etcmachineid
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: fluent-bit
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /etc/machine-id
            type: File
          name: etcmachineid
{{ end }}
