apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloud-robotics
spec:
  secretName: tls
  issuerRef:
    name: letsencrypt-prod
  commonName: {{ .Values.domain }}
  dnsNames:
    - {{ .Values.domain }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.domain }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
spec:
  isCA: true
  duration: 8760h # 1year. This needs to be at least 3x 90days
  commonName: {{ .Values.domain }}
  secretName: cluster-authority
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
