{{ range .Values.robots }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-federation-{{ .name }}
  labels:
    prometheus: kube-prometheus
spec:
  endpoints:
  - port: http
    path: /client/{{ .name }}/federate
    params:
      'match[]':
      # Identified via Prometheus query: topk(10, count by (__name__)({__name__=~".+"}))
      # As of 2021-07-21 this config reduces the number of time series scraped by approx 1/4
      - '{__name__=~".+", __name__!~"apiserver_request_duration_seconds_bucket|etcd_request_duration_seconds_bucket|apiserver_response_sizes_bucket"}'
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: instance
  # These are the labels below on the federation service
  targetLabels:
  - robot
  - cluster
  selector:
    matchLabels:
      app: prometheus-federation
      robot: "{{ .name }}"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-federation-{{ .name }}
  labels:
    app: prometheus-federation
    robot: "{{ .name }}"
    cluster: "{{ .name }}"
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: prometheus-relay-server
  type: ClusterIP
---
{{ end }}
