apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubernetes-relay-server
  labels:
    prometheus: kube-prometheus
spec:
  endpoints:
  - port: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: instance
  selector:
    matchLabels:
      app: kubernetes-relay-server
