image:
  pullPolicy: IfNotPresent

env:
   - name: MY_NODE_NAME
     valueFrom:
       fieldRef:
         fieldPath: spec.nodeName

## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag k8s_node.${MY_NODE_NAME}
        Read_From_Tail On

    [INPUT]
        name            node_exporter_metrics
        tag             node_metrics
        scrape_interval 10

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals level info
        Add severity INFO

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals level warning
        Add severity WARNING

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals level warn
        Add severity WARNING

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals level error
        Add severity ERROR

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log ^.*\[\sinfo\].*$
        Add severity INFO

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log ^.*\[\swarn\].*$
        Add severity WARNING

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log .*\[error\].*
        Add severity ERROR

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log .*(type="Info"|level=info).*
        Add severity INFO

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log .*(type="Warning"|level=warning).*
        Add severity WARNING

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_matches log .*(type="Error"|level=error).*
        Add severity ERROR

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals stream stderr
        Add severity ERROR

    [FILTER]
        Name          modify
        Match         kube.*
        Condition Key_value_equals stream stdout
        Add severity INFO

    [FILTER]
        Name          modify
        Match         kube.*
        Remove _p

    [FILTER]
        Name          modify
        Match         kube.*
        Rename log message

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name stackdriver
        Match kube.*
        Tag_Prefix kube.var.log.containers.
        Resource k8s_container
        k8s_cluster_name MY_ROBOT
        k8s_cluster_location MY_CLUSTER_LOCATION
        severity_key severity
        Workers 1

    [OUTPUT]
        Name stackdriver
        Match k8s_node.*
        Resource k8s_node
        k8s_cluster_name MY_ROBOT
        k8s_cluster_location MY_CLUSTER_LOCATION
        Workers 1

    [OUTPUT]
        name            prometheus_exporter
        match           node_metrics
        port            24231

volumeMounts:
  - name: config
    mountPath: /fluent-bit/etc/fluent-bit.conf
    subPath: fluent-bit.conf

daemonSetVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: etcmachineid
    hostPath:
      path: /etc/machine-id
      type: File

daemonSetVolumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: etcmachineid
    mountPath: /etc/machine-id
    readOnly: true

